[2022-06-15 22:11:30,589] logger.py-->print_log line:17 [INFO] ----------接口测试开始-----------
[2022-06-15 22:11:30,589] logger.py-->print_log line:17 [INFO] 获取随机数获取admin用户随机数-成功
[2022-06-15 22:11:30,589] logger.py-->print_log line:17 [INFO] 接口请求方式post
[2022-06-15 22:11:30,589] logger.py-->print_log line:17 [INFO] 接口请求路径http://jazz.wifi/api.cgi?path=account&method=get_rand
[2022-06-15 22:11:30,589] logger.py-->print_log line:17 [INFO] 接口请求参数{'json': {'type': 'admin', 'user_id': 'RpEbrYZk'}}
[2022-06-15 22:11:30,589] logger.py-->print_log line:17 [INFO] 接口请求参数{'headers': {'Origin': 'http://192.168.2.1', 'Referer': 'http://jazz.wifi/index.htm\\r\\n', 'X-Requested-With': 'XMLHttpRequest', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36'}}
[2022-06-15 22:11:41,633] logger.py-->error_log line:11 [ERROR] 发送请求报错HTTPConnectionPool(host='jazz.wifi', port=80): Max retries exceeded with url: /api.cgi?path=account&method=get_rand (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F4E9D35700>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
[2022-06-15 22:11:41,633] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:11:41,836] logger.py-->print_log line:17 [INFO] ----------接口测试开始-----------
[2022-06-15 22:11:41,836] logger.py-->print_log line:17 [INFO] 获取随机数获取admin用户随机数-type空
[2022-06-15 22:11:41,836] logger.py-->print_log line:17 [INFO] 接口请求方式post
[2022-06-15 22:11:41,836] logger.py-->print_log line:17 [INFO] 接口请求路径http://jazz.wifi/api.cgi?path=account&method=get_rand
[2022-06-15 22:11:41,836] logger.py-->print_log line:17 [INFO] 接口请求参数{'json': {'type': '', 'user_id': 'RpEbrYZk'}}
[2022-06-15 22:11:41,836] logger.py-->print_log line:17 [INFO] 接口请求参数{'headers': {'Origin': 'http://192.168.2.1', 'Referer': 'http://jazz.wifi/index.htm\\r\\n', 'X-Requested-With': 'XMLHttpRequest', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36'}}
[2022-06-15 22:11:41,836] logger.py-->error_log line:11 [ERROR] 发送请求报错HTTPConnectionPool(host='jazz.wifi', port=80): Max retries exceeded with url: /api.cgi?path=account&method=get_rand (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F4EA9548B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
[2022-06-15 22:11:41,836] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:11:41,946] logger.py-->print_log line:17 [INFO] ----------接口测试开始-----------
[2022-06-15 22:11:41,946] logger.py-->print_log line:17 [INFO] 获取随机数获取admin用户随机数-user_id空
[2022-06-15 22:11:41,946] logger.py-->print_log line:17 [INFO] 接口请求方式post
[2022-06-15 22:11:41,946] logger.py-->print_log line:17 [INFO] 接口请求路径http://jazz.wifi/api.cgi?path=account&method=get_rand
[2022-06-15 22:11:41,946] logger.py-->print_log line:17 [INFO] 接口请求参数{'json': {'type': 'admin', 'user_id': ''}}
[2022-06-15 22:11:41,946] logger.py-->print_log line:17 [INFO] 接口请求参数{'headers': {'Origin': 'http://192.168.2.1', 'Referer': 'http://jazz.wifi/index.htm\\r\\n', 'X-Requested-With': 'XMLHttpRequest', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36'}}
[2022-06-15 22:11:41,946] logger.py-->error_log line:11 [ERROR] 发送请求报错HTTPConnectionPool(host='jazz.wifi', port=80): Max retries exceeded with url: /api.cgi?path=account&method=get_rand (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F4EA0984F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
[2022-06-15 22:11:41,946] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:11:42,070] logger.py-->print_log line:17 [INFO] ----------接口测试开始-----------
[2022-06-15 22:11:42,070] logger.py-->print_log line:17 [INFO] 获取随机数获取sdcard用户随机数-type空
[2022-06-15 22:11:42,070] logger.py-->print_log line:17 [INFO] 接口请求方式post
[2022-06-15 22:11:42,070] logger.py-->print_log line:17 [INFO] 接口请求路径http://jazz.wifi/api.cgi?path=account&method=get_rand
[2022-06-15 22:11:42,070] logger.py-->print_log line:17 [INFO] 接口请求参数{'json': {'type': '', 'user_id': 'RpEbrYZk'}}
[2022-06-15 22:11:42,070] logger.py-->print_log line:17 [INFO] 接口请求参数{'headers': {'Origin': 'http://192.168.2.1', 'Referer': 'http://jazz.wifi/index.htm\\r\\n', 'X-Requested-With': 'XMLHttpRequest', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36'}}
[2022-06-15 22:11:42,070] logger.py-->error_log line:11 [ERROR] 发送请求报错HTTPConnectionPool(host='jazz.wifi', port=80): Max retries exceeded with url: /api.cgi?path=account&method=get_rand (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F4EA1226A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
[2022-06-15 22:11:42,070] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:11:42,180] logger.py-->print_log line:17 [INFO] ----------接口测试开始-----------
[2022-06-15 22:11:42,180] logger.py-->print_log line:17 [INFO] 获取随机数获取sdcard用户随机数-user_id空
[2022-06-15 22:11:42,180] logger.py-->print_log line:17 [INFO] 接口请求方式post
[2022-06-15 22:11:42,180] logger.py-->print_log line:17 [INFO] 接口请求路径http://jazz.wifi/api.cgi?path=account&method=get_rand
[2022-06-15 22:11:42,180] logger.py-->print_log line:17 [INFO] 接口请求参数{'json': {'type': 'sdcard', 'user_id': ''}}
[2022-06-15 22:11:42,180] logger.py-->print_log line:17 [INFO] 接口请求参数{'headers': {'Origin': 'http://192.168.2.1', 'Referer': 'http://jazz.wifi/index.htm\\r\\n', 'X-Requested-With': 'XMLHttpRequest', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36'}}
[2022-06-15 22:11:42,180] logger.py-->error_log line:11 [ERROR] 发送请求报错HTTPConnectionPool(host='jazz.wifi', port=80): Max retries exceeded with url: /api.cgi?path=account&method=get_rand (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F4EA0444C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
[2022-06-15 22:11:42,180] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:11:42,289] logger.py-->print_log line:17 [INFO] ----------接口测试开始-----------
[2022-06-15 22:11:42,289] logger.py-->print_log line:17 [INFO] 获取随机数获取admin用户随机数-成功
[2022-06-15 22:11:42,289] logger.py-->print_log line:17 [INFO] 接口请求方式post
[2022-06-15 22:11:42,289] logger.py-->print_log line:17 [INFO] 接口请求路径http://jazz.wifi/api.cgi?path=account&method=get_rand
[2022-06-15 22:11:42,289] logger.py-->print_log line:17 [INFO] 接口请求参数{'json': {'type': 'admin', 'user_id': 'RpEbrYZk'}}
[2022-06-15 22:11:42,289] logger.py-->print_log line:17 [INFO] 接口请求参数{'headers': {'Origin': 'http://192.168.2.1', 'Referer': 'http://jazz.wifi/index.htm\\r\\n', 'X-Requested-With': 'XMLHttpRequest', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36'}}
[2022-06-15 22:11:42,289] logger.py-->error_log line:11 [ERROR] 发送请求报错HTTPConnectionPool(host='jazz.wifi', port=80): Max retries exceeded with url: /api.cgi?path=account&method=get_rand (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F4EA9E4A00>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
[2022-06-15 22:11:42,289] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:11:42,399] logger.py-->print_log line:17 [INFO] ----------接口测试开始-----------
[2022-06-15 22:11:42,399] logger.py-->print_log line:17 [INFO] MD5登录admin登录-成功
[2022-06-15 22:11:42,399] logger.py-->print_log line:17 [INFO] 接口请求方式post
[2022-06-15 22:11:42,399] logger.py-->print_log line:17 [INFO] 接口请求路径http://jazz.wifi/api.cgi?path=account&method=login
[2022-06-15 22:11:42,399] logger.py-->error_log line:11 [ERROR] 热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:11:42,399] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:11:42,399] logger.py-->error_log line:11 [ERROR] 热加载报错热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:11:42,399] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:11:42,399] logger.py-->error_log line:11 [ERROR] 发送请求报错热加载报错热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:11:42,399] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:11:42,430] logger.py-->print_log line:17 [INFO] ----------接口测试开始-----------
[2022-06-15 22:11:42,430] logger.py-->print_log line:17 [INFO] MD5登录admin登录-username为空
[2022-06-15 22:11:42,430] logger.py-->print_log line:17 [INFO] 接口请求方式post
[2022-06-15 22:11:42,430] logger.py-->print_log line:17 [INFO] 接口请求路径http://jazz.wifi/api.cgi?path=account&method=login
[2022-06-15 22:11:42,430] logger.py-->error_log line:11 [ERROR] 热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:11:42,430] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:11:42,430] logger.py-->error_log line:11 [ERROR] 热加载报错热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:11:42,430] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:11:42,430] logger.py-->error_log line:11 [ERROR] 发送请求报错热加载报错热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:11:42,430] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:11:42,445] logger.py-->print_log line:17 [INFO] ----------接口测试开始-----------
[2022-06-15 22:11:42,445] logger.py-->print_log line:17 [INFO] MD5登录admin登录-password为空
[2022-06-15 22:11:42,445] logger.py-->print_log line:17 [INFO] 接口请求方式post
[2022-06-15 22:11:42,445] logger.py-->print_log line:17 [INFO] 接口请求路径http://jazz.wifi/api.cgi?path=account&method=login
[2022-06-15 22:11:42,445] logger.py-->print_log line:17 [INFO] 接口请求参数{'json': {'type': 'admin', 'username': 'admin', 'password': '', 'user_id': 'RpEbrYZk'}}
[2022-06-15 22:11:42,445] logger.py-->print_log line:17 [INFO] 接口请求参数{'headers': {'Origin': 'http://192.168.2.1', 'Referer': 'http://jazz.wifi/index.htm\\r\\n', 'X-Requested-With': 'XMLHttpRequest', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36'}}
[2022-06-15 22:11:42,461] logger.py-->error_log line:11 [ERROR] 发送请求报错HTTPConnectionPool(host='jazz.wifi', port=80): Max retries exceeded with url: /api.cgi?path=account&method=login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F4E9E72700>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
[2022-06-15 22:11:42,461] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:11:42,555] logger.py-->print_log line:17 [INFO] ----------接口测试开始-----------
[2022-06-15 22:11:42,555] logger.py-->print_log line:17 [INFO] MD5登录admin登录-user_id为空
[2022-06-15 22:11:42,555] logger.py-->print_log line:17 [INFO] 接口请求方式post
[2022-06-15 22:11:42,555] logger.py-->print_log line:17 [INFO] 接口请求路径http://jazz.wifi/api.cgi?path=account&method=login
[2022-06-15 22:11:42,555] logger.py-->error_log line:11 [ERROR] 热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:11:42,555] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:11:42,555] logger.py-->error_log line:11 [ERROR] 热加载报错热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:11:42,555] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:11:42,555] logger.py-->error_log line:11 [ERROR] 发送请求报错热加载报错热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:11:42,555] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:11:42,586] logger.py-->print_log line:17 [INFO] ----------接口测试开始-----------
[2022-06-15 22:11:42,586] logger.py-->print_log line:17 [INFO] MD5登录admin登录-type为空
[2022-06-15 22:11:42,586] logger.py-->print_log line:17 [INFO] 接口请求方式post
[2022-06-15 22:11:42,586] logger.py-->print_log line:17 [INFO] 接口请求路径http://jazz.wifi/api.cgi?path=account&method=login
[2022-06-15 22:11:42,586] logger.py-->error_log line:11 [ERROR] 热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:11:42,586] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:11:42,586] logger.py-->error_log line:11 [ERROR] 热加载报错热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:11:42,586] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:11:42,586] logger.py-->error_log line:11 [ERROR] 发送请求报错热加载报错热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:11:42,586] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:11:42,602] logger.py-->print_log line:17 [INFO] ----------接口测试开始-----------
[2022-06-15 22:11:42,602] logger.py-->print_log line:17 [INFO] MD5登录sdcard登录-成功
[2022-06-15 22:11:42,602] logger.py-->print_log line:17 [INFO] 接口请求方式post
[2022-06-15 22:11:42,602] logger.py-->print_log line:17 [INFO] 接口请求路径http://jazz.wifi/api.cgi?path=account&method=login
[2022-06-15 22:11:42,602] logger.py-->error_log line:11 [ERROR] 热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:11:42,602] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:11:42,602] logger.py-->error_log line:11 [ERROR] 热加载报错热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:11:42,602] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:11:42,602] logger.py-->error_log line:11 [ERROR] 发送请求报错热加载报错热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:11:42,602] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:11:42,633] logger.py-->print_log line:17 [INFO] ----------接口测试开始-----------
[2022-06-15 22:11:42,633] logger.py-->print_log line:17 [INFO] MD5登录sdcard登录-username为空
[2022-06-15 22:11:42,633] logger.py-->print_log line:17 [INFO] 接口请求方式post
[2022-06-15 22:11:42,633] logger.py-->print_log line:17 [INFO] 接口请求路径http://jazz.wifi/api.cgi?path=account&method=login
[2022-06-15 22:11:42,633] logger.py-->error_log line:11 [ERROR] 热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:11:42,633] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:11:42,633] logger.py-->error_log line:11 [ERROR] 热加载报错热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:11:42,633] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:11:42,633] logger.py-->error_log line:11 [ERROR] 发送请求报错热加载报错热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:11:42,633] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:11:42,648] logger.py-->print_log line:17 [INFO] ----------接口测试开始-----------
[2022-06-15 22:11:42,648] logger.py-->print_log line:17 [INFO] MD5登录sdcard登录-password为空
[2022-06-15 22:11:42,648] logger.py-->print_log line:17 [INFO] 接口请求方式post
[2022-06-15 22:11:42,648] logger.py-->print_log line:17 [INFO] 接口请求路径http://jazz.wifi/api.cgi?path=account&method=login
[2022-06-15 22:11:42,648] logger.py-->print_log line:17 [INFO] 接口请求参数{'json': {'type': 'sdcard', 'username': 'sdcard', 'password': '', 'user_id': 'RpEbrYZk'}}
[2022-06-15 22:11:42,648] logger.py-->print_log line:17 [INFO] 接口请求参数{'headers': {'Origin': 'http://192.168.2.1', 'Referer': 'http://jazz.wifi/index.htm\\r\\n', 'X-Requested-With': 'XMLHttpRequest', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36'}}
[2022-06-15 22:11:42,648] logger.py-->error_log line:11 [ERROR] 发送请求报错HTTPConnectionPool(host='jazz.wifi', port=80): Max retries exceeded with url: /api.cgi?path=account&method=login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F4EA9E2940>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
[2022-06-15 22:11:42,648] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:11:42,758] logger.py-->print_log line:17 [INFO] ----------接口测试开始-----------
[2022-06-15 22:11:42,758] logger.py-->print_log line:17 [INFO] MD5登录sdcard登录-user_id为空
[2022-06-15 22:11:42,758] logger.py-->print_log line:17 [INFO] 接口请求方式post
[2022-06-15 22:11:42,758] logger.py-->print_log line:17 [INFO] 接口请求路径http://jazz.wifi/api.cgi?path=account&method=login
[2022-06-15 22:11:42,758] logger.py-->error_log line:11 [ERROR] 热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:11:42,758] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:11:42,758] logger.py-->error_log line:11 [ERROR] 热加载报错热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:11:42,758] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:11:42,758] logger.py-->error_log line:11 [ERROR] 发送请求报错热加载报错热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:11:42,758] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:11:42,789] logger.py-->print_log line:17 [INFO] ----------接口测试开始-----------
[2022-06-15 22:11:42,789] logger.py-->print_log line:17 [INFO] MD5登录sdcard登录-type为空
[2022-06-15 22:11:42,789] logger.py-->print_log line:17 [INFO] 接口请求方式post
[2022-06-15 22:11:42,789] logger.py-->print_log line:17 [INFO] 接口请求路径http://jazz.wifi/api.cgi?path=account&method=login
[2022-06-15 22:11:42,789] logger.py-->error_log line:11 [ERROR] 热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:11:42,789] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:11:42,789] logger.py-->error_log line:11 [ERROR] 热加载报错热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:11:42,789] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:11:42,789] logger.py-->error_log line:11 [ERROR] 发送请求报错热加载报错热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:11:42,789] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:11:42,805] logger.py-->print_log line:17 [INFO] ----------接口测试开始-----------
[2022-06-15 22:11:42,805] logger.py-->print_log line:17 [INFO] 获取登录信息
[2022-06-15 22:11:42,805] logger.py-->print_log line:17 [INFO] 接口请求方式post
[2022-06-15 22:11:42,805] logger.py-->print_log line:17 [INFO] 接口请求路径http://jazz.wifi/api.cgi?path=account&method=get_info
[2022-06-15 22:11:42,805] logger.py-->error_log line:11 [ERROR] 热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:11:42,805] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:11:42,805] logger.py-->error_log line:11 [ERROR] 热加载报错热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:11:42,805] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:11:42,805] logger.py-->error_log line:11 [ERROR] 发送请求报错热加载报错热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:11:42,805] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:11:42,836] logger.py-->print_log line:17 [INFO] ----------接口测试开始-----------
[2022-06-15 22:11:42,836] logger.py-->print_log line:17 [INFO] 获取登陆剩余尝试次数和超出次数的锁定时间
[2022-06-15 22:11:42,836] logger.py-->print_log line:17 [INFO] 接口请求方式post
[2022-06-15 22:11:42,836] logger.py-->print_log line:17 [INFO] 接口请求路径http://jazz.wifi/api.cgi?path=account&method=get_login_status
[2022-06-15 22:11:42,836] logger.py-->error_log line:11 [ERROR] 热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:11:42,836] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:11:42,836] logger.py-->error_log line:11 [ERROR] 热加载报错热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:11:42,836] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:11:42,836] logger.py-->error_log line:11 [ERROR] 发送请求报错热加载报错热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:11:42,836] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:11:42,852] logger.py-->print_log line:17 [INFO] ----------接口测试开始-----------
[2022-06-15 22:11:42,852] logger.py-->print_log line:17 [INFO] 获取登录信息
[2022-06-15 22:11:42,852] logger.py-->print_log line:17 [INFO] 接口请求方式post
[2022-06-15 22:11:42,852] logger.py-->print_log line:17 [INFO] 接口请求路径http://jazz.wifi/api.cgi?path=account&method=set_info
[2022-06-15 22:11:42,852] logger.py-->print_log line:17 [INFO] 接口请求参数{'json': {'type': 'admin', 'username': 'admin', 'password': 'admin', 'total_time': 300}}
[2022-06-15 22:11:42,852] logger.py-->print_log line:17 [INFO] 接口请求参数{'headers': {'Origin': 'http://192.168.2.1', 'Referer': 'http://jazz.wifi/index.htm\\r\\n', 'X-Requested-With': 'XMLHttpRequest', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36'}}
[2022-06-15 22:11:42,852] logger.py-->error_log line:11 [ERROR] 发送请求报错HTTPConnectionPool(host='jazz.wifi', port=80): Max retries exceeded with url: /api.cgi?path=account&method=set_info (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F4E9EF9400>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
[2022-06-15 22:11:42,852] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:11:42,961] logger.py-->print_log line:17 [INFO] ----------接口测试开始-----------
[2022-06-15 22:11:42,961] logger.py-->print_log line:17 [INFO] 获取登陆剩余尝试次数和超出次数的锁定时间
[2022-06-15 22:11:42,961] logger.py-->print_log line:17 [INFO] 接口请求方式post
[2022-06-15 22:11:42,961] logger.py-->print_log line:17 [INFO] 接口请求路径http://jazz.wifi/api.cgi?path=account&method=get_retrytimes_and_time
[2022-06-15 22:11:42,961] logger.py-->print_log line:17 [INFO] 接口请求参数{'json': {'type': 'admin'}}
[2022-06-15 22:11:42,961] logger.py-->print_log line:17 [INFO] 接口请求参数{'headers': {'Origin': 'http://192.168.2.1', 'Referer': 'http://jazz.wifi/index.htm\\r\\n', 'X-Requested-With': 'XMLHttpRequest', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36'}}
[2022-06-15 22:11:42,961] logger.py-->error_log line:11 [ERROR] 发送请求报错HTTPConnectionPool(host='jazz.wifi', port=80): Max retries exceeded with url: /api.cgi?path=account&method=get_retrytimes_and_time (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F4EAA78640>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
[2022-06-15 22:11:42,961] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

