[2022-06-15 22:12:00,113] logger.py-->print_log line:17 [INFO] ----------接口测试开始-----------
[2022-06-15 22:12:00,113] logger.py-->print_log line:17 [INFO] 获取随机数获取admin用户随机数-成功
[2022-06-15 22:12:00,113] logger.py-->print_log line:17 [INFO] 接口请求方式post
[2022-06-15 22:12:00,113] logger.py-->print_log line:17 [INFO] 接口请求路径http://jazz.wifi/api.cgi?path=account&method=get_rand
[2022-06-15 22:12:00,113] logger.py-->print_log line:17 [INFO] 接口请求参数{'json': {'type': 'admin', 'user_id': 'RpEbrYZk'}}
[2022-06-15 22:12:00,113] logger.py-->print_log line:17 [INFO] 接口请求参数{'headers': {'Origin': 'http://192.168.2.1', 'Referer': 'http://jazz.wifi/index.htm\\r\\n', 'X-Requested-With': 'XMLHttpRequest', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36'}}
[2022-06-15 22:12:00,113] logger.py-->error_log line:11 [ERROR] 发送请求报错HTTPConnectionPool(host='jazz.wifi', port=80): Max retries exceeded with url: /api.cgi?path=account&method=get_rand (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C7ADE86A00>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
[2022-06-15 22:12:00,113] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:12:00,363] logger.py-->print_log line:17 [INFO] ----------接口测试开始-----------
[2022-06-15 22:12:00,363] logger.py-->print_log line:17 [INFO] 获取随机数获取admin用户随机数-type空
[2022-06-15 22:12:00,363] logger.py-->print_log line:17 [INFO] 接口请求方式post
[2022-06-15 22:12:00,363] logger.py-->print_log line:17 [INFO] 接口请求路径http://jazz.wifi/api.cgi?path=account&method=get_rand
[2022-06-15 22:12:00,363] logger.py-->print_log line:17 [INFO] 接口请求参数{'json': {'type': '', 'user_id': 'RpEbrYZk'}}
[2022-06-15 22:12:00,363] logger.py-->print_log line:17 [INFO] 接口请求参数{'headers': {'Origin': 'http://192.168.2.1', 'Referer': 'http://jazz.wifi/index.htm\\r\\n', 'X-Requested-With': 'XMLHttpRequest', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36'}}
[2022-06-15 22:12:00,363] logger.py-->error_log line:11 [ERROR] 发送请求报错HTTPConnectionPool(host='jazz.wifi', port=80): Max retries exceeded with url: /api.cgi?path=account&method=get_rand (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C7AE1DC760>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
[2022-06-15 22:12:00,363] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:12:00,472] logger.py-->print_log line:17 [INFO] ----------接口测试开始-----------
[2022-06-15 22:12:00,472] logger.py-->print_log line:17 [INFO] 获取随机数获取admin用户随机数-user_id空
[2022-06-15 22:12:00,472] logger.py-->print_log line:17 [INFO] 接口请求方式post
[2022-06-15 22:12:00,472] logger.py-->print_log line:17 [INFO] 接口请求路径http://jazz.wifi/api.cgi?path=account&method=get_rand
[2022-06-15 22:12:00,472] logger.py-->print_log line:17 [INFO] 接口请求参数{'json': {'type': 'admin', 'user_id': ''}}
[2022-06-15 22:12:00,472] logger.py-->print_log line:17 [INFO] 接口请求参数{'headers': {'Origin': 'http://192.168.2.1', 'Referer': 'http://jazz.wifi/index.htm\\r\\n', 'X-Requested-With': 'XMLHttpRequest', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36'}}
[2022-06-15 22:12:00,472] logger.py-->error_log line:11 [ERROR] 发送请求报错HTTPConnectionPool(host='jazz.wifi', port=80): Max retries exceeded with url: /api.cgi?path=account&method=get_rand (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C7AE068C40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
[2022-06-15 22:12:00,472] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:12:00,597] logger.py-->print_log line:17 [INFO] ----------接口测试开始-----------
[2022-06-15 22:12:00,597] logger.py-->print_log line:17 [INFO] 获取随机数获取sdcard用户随机数-type空
[2022-06-15 22:12:00,597] logger.py-->print_log line:17 [INFO] 接口请求方式post
[2022-06-15 22:12:00,597] logger.py-->print_log line:17 [INFO] 接口请求路径http://jazz.wifi/api.cgi?path=account&method=get_rand
[2022-06-15 22:12:00,597] logger.py-->print_log line:17 [INFO] 接口请求参数{'json': {'type': '', 'user_id': 'RpEbrYZk'}}
[2022-06-15 22:12:00,597] logger.py-->print_log line:17 [INFO] 接口请求参数{'headers': {'Origin': 'http://192.168.2.1', 'Referer': 'http://jazz.wifi/index.htm\\r\\n', 'X-Requested-With': 'XMLHttpRequest', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36'}}
[2022-06-15 22:12:00,597] logger.py-->error_log line:11 [ERROR] 发送请求报错HTTPConnectionPool(host='jazz.wifi', port=80): Max retries exceeded with url: /api.cgi?path=account&method=get_rand (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C7AEA697C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
[2022-06-15 22:12:00,597] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:12:00,707] logger.py-->print_log line:17 [INFO] ----------接口测试开始-----------
[2022-06-15 22:12:00,707] logger.py-->print_log line:17 [INFO] 获取随机数获取sdcard用户随机数-user_id空
[2022-06-15 22:12:00,707] logger.py-->print_log line:17 [INFO] 接口请求方式post
[2022-06-15 22:12:00,707] logger.py-->print_log line:17 [INFO] 接口请求路径http://jazz.wifi/api.cgi?path=account&method=get_rand
[2022-06-15 22:12:00,707] logger.py-->print_log line:17 [INFO] 接口请求参数{'json': {'type': 'sdcard', 'user_id': ''}}
[2022-06-15 22:12:00,707] logger.py-->print_log line:17 [INFO] 接口请求参数{'headers': {'Origin': 'http://192.168.2.1', 'Referer': 'http://jazz.wifi/index.htm\\r\\n', 'X-Requested-With': 'XMLHttpRequest', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36'}}
[2022-06-15 22:12:00,707] logger.py-->error_log line:11 [ERROR] 发送请求报错HTTPConnectionPool(host='jazz.wifi', port=80): Max retries exceeded with url: /api.cgi?path=account&method=get_rand (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C7AEA1ECD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
[2022-06-15 22:12:00,707] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:12:00,816] logger.py-->print_log line:17 [INFO] ----------接口测试开始-----------
[2022-06-15 22:12:00,816] logger.py-->print_log line:17 [INFO] 获取随机数获取admin用户随机数-成功
[2022-06-15 22:12:00,816] logger.py-->print_log line:17 [INFO] 接口请求方式post
[2022-06-15 22:12:00,816] logger.py-->print_log line:17 [INFO] 接口请求路径http://jazz.wifi/api.cgi?path=account&method=get_rand
[2022-06-15 22:12:00,816] logger.py-->print_log line:17 [INFO] 接口请求参数{'json': {'type': 'admin', 'user_id': 'RpEbrYZk'}}
[2022-06-15 22:12:00,816] logger.py-->print_log line:17 [INFO] 接口请求参数{'headers': {'Origin': 'http://192.168.2.1', 'Referer': 'http://jazz.wifi/index.htm\\r\\n', 'X-Requested-With': 'XMLHttpRequest', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36'}}
[2022-06-15 22:12:00,816] logger.py-->error_log line:11 [ERROR] 发送请求报错HTTPConnectionPool(host='jazz.wifi', port=80): Max retries exceeded with url: /api.cgi?path=account&method=get_rand (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C7AEB47610>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
[2022-06-15 22:12:00,816] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:12:00,941] logger.py-->print_log line:17 [INFO] ----------接口测试开始-----------
[2022-06-15 22:12:00,941] logger.py-->print_log line:17 [INFO] MD5登录admin登录-成功
[2022-06-15 22:12:00,941] logger.py-->print_log line:17 [INFO] 接口请求方式post
[2022-06-15 22:12:00,941] logger.py-->print_log line:17 [INFO] 接口请求路径http://jazz.wifi/api.cgi?path=account&method=login
[2022-06-15 22:12:00,941] logger.py-->error_log line:11 [ERROR] 热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:12:00,941] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:12:00,941] logger.py-->error_log line:11 [ERROR] 热加载报错热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:12:00,941] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:12:00,941] logger.py-->error_log line:11 [ERROR] 发送请求报错热加载报错热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:12:00,941] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:12:00,957] logger.py-->print_log line:17 [INFO] ----------接口测试开始-----------
[2022-06-15 22:12:00,957] logger.py-->print_log line:17 [INFO] MD5登录admin登录-username为空
[2022-06-15 22:12:00,957] logger.py-->print_log line:17 [INFO] 接口请求方式post
[2022-06-15 22:12:00,957] logger.py-->print_log line:17 [INFO] 接口请求路径http://jazz.wifi/api.cgi?path=account&method=login
[2022-06-15 22:12:00,957] logger.py-->error_log line:11 [ERROR] 热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:12:00,957] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:12:00,957] logger.py-->error_log line:11 [ERROR] 热加载报错热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:12:00,957] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:12:00,957] logger.py-->error_log line:11 [ERROR] 发送请求报错热加载报错热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:12:00,957] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:12:00,988] logger.py-->print_log line:17 [INFO] ----------接口测试开始-----------
[2022-06-15 22:12:00,988] logger.py-->print_log line:17 [INFO] MD5登录admin登录-password为空
[2022-06-15 22:12:00,988] logger.py-->print_log line:17 [INFO] 接口请求方式post
[2022-06-15 22:12:00,988] logger.py-->print_log line:17 [INFO] 接口请求路径http://jazz.wifi/api.cgi?path=account&method=login
[2022-06-15 22:12:00,988] logger.py-->print_log line:17 [INFO] 接口请求参数{'json': {'type': 'admin', 'username': 'admin', 'password': '', 'user_id': 'RpEbrYZk'}}
[2022-06-15 22:12:00,988] logger.py-->print_log line:17 [INFO] 接口请求参数{'headers': {'Origin': 'http://192.168.2.1', 'Referer': 'http://jazz.wifi/index.htm\\r\\n', 'X-Requested-With': 'XMLHttpRequest', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36'}}
[2022-06-15 22:12:00,988] logger.py-->error_log line:11 [ERROR] 发送请求报错HTTPConnectionPool(host='jazz.wifi', port=80): Max retries exceeded with url: /api.cgi?path=account&method=login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C7ADFF1160>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
[2022-06-15 22:12:00,988] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:12:01,098] logger.py-->print_log line:17 [INFO] ----------接口测试开始-----------
[2022-06-15 22:12:01,098] logger.py-->print_log line:17 [INFO] MD5登录admin登录-user_id为空
[2022-06-15 22:12:01,098] logger.py-->print_log line:17 [INFO] 接口请求方式post
[2022-06-15 22:12:01,098] logger.py-->print_log line:17 [INFO] 接口请求路径http://jazz.wifi/api.cgi?path=account&method=login
[2022-06-15 22:12:01,098] logger.py-->error_log line:11 [ERROR] 热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:12:01,098] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:12:01,098] logger.py-->error_log line:11 [ERROR] 热加载报错热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:12:01,098] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:12:01,098] logger.py-->error_log line:11 [ERROR] 发送请求报错热加载报错热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:12:01,098] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:12:01,113] logger.py-->print_log line:17 [INFO] ----------接口测试开始-----------
[2022-06-15 22:12:01,113] logger.py-->print_log line:17 [INFO] MD5登录admin登录-type为空
[2022-06-15 22:12:01,113] logger.py-->print_log line:17 [INFO] 接口请求方式post
[2022-06-15 22:12:01,113] logger.py-->print_log line:17 [INFO] 接口请求路径http://jazz.wifi/api.cgi?path=account&method=login
[2022-06-15 22:12:01,113] logger.py-->error_log line:11 [ERROR] 热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:12:01,113] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:12:01,113] logger.py-->error_log line:11 [ERROR] 热加载报错热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:12:01,113] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:12:01,113] logger.py-->error_log line:11 [ERROR] 发送请求报错热加载报错热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:12:01,113] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:12:01,144] logger.py-->print_log line:17 [INFO] ----------接口测试开始-----------
[2022-06-15 22:12:01,144] logger.py-->print_log line:17 [INFO] MD5登录sdcard登录-成功
[2022-06-15 22:12:01,144] logger.py-->print_log line:17 [INFO] 接口请求方式post
[2022-06-15 22:12:01,144] logger.py-->print_log line:17 [INFO] 接口请求路径http://jazz.wifi/api.cgi?path=account&method=login
[2022-06-15 22:12:01,144] logger.py-->error_log line:11 [ERROR] 热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:12:01,144] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:12:01,144] logger.py-->error_log line:11 [ERROR] 热加载报错热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:12:01,144] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:12:01,144] logger.py-->error_log line:11 [ERROR] 发送请求报错热加载报错热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:12:01,144] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:12:01,160] logger.py-->print_log line:17 [INFO] ----------接口测试开始-----------
[2022-06-15 22:12:01,160] logger.py-->print_log line:17 [INFO] MD5登录sdcard登录-username为空
[2022-06-15 22:12:01,160] logger.py-->print_log line:17 [INFO] 接口请求方式post
[2022-06-15 22:12:01,160] logger.py-->print_log line:17 [INFO] 接口请求路径http://jazz.wifi/api.cgi?path=account&method=login
[2022-06-15 22:12:01,160] logger.py-->error_log line:11 [ERROR] 热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:12:01,160] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:12:01,160] logger.py-->error_log line:11 [ERROR] 热加载报错热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:12:01,160] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:12:01,160] logger.py-->error_log line:11 [ERROR] 发送请求报错热加载报错热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:12:01,160] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:12:01,176] logger.py-->print_log line:17 [INFO] ----------接口测试开始-----------
[2022-06-15 22:12:01,176] logger.py-->print_log line:17 [INFO] MD5登录sdcard登录-password为空
[2022-06-15 22:12:01,176] logger.py-->print_log line:17 [INFO] 接口请求方式post
[2022-06-15 22:12:01,191] logger.py-->print_log line:17 [INFO] 接口请求路径http://jazz.wifi/api.cgi?path=account&method=login
[2022-06-15 22:12:01,191] logger.py-->print_log line:17 [INFO] 接口请求参数{'json': {'type': 'sdcard', 'username': 'sdcard', 'password': '', 'user_id': 'RpEbrYZk'}}
[2022-06-15 22:12:01,191] logger.py-->print_log line:17 [INFO] 接口请求参数{'headers': {'Origin': 'http://192.168.2.1', 'Referer': 'http://jazz.wifi/index.htm\\r\\n', 'X-Requested-With': 'XMLHttpRequest', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36'}}
[2022-06-15 22:12:01,191] logger.py-->error_log line:11 [ERROR] 发送请求报错HTTPConnectionPool(host='jazz.wifi', port=80): Max retries exceeded with url: /api.cgi?path=account&method=login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C7AEB56C40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
[2022-06-15 22:12:01,191] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:12:01,301] logger.py-->print_log line:17 [INFO] ----------接口测试开始-----------
[2022-06-15 22:12:01,301] logger.py-->print_log line:17 [INFO] MD5登录sdcard登录-user_id为空
[2022-06-15 22:12:01,301] logger.py-->print_log line:17 [INFO] 接口请求方式post
[2022-06-15 22:12:01,301] logger.py-->print_log line:17 [INFO] 接口请求路径http://jazz.wifi/api.cgi?path=account&method=login
[2022-06-15 22:12:01,301] logger.py-->error_log line:11 [ERROR] 热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:12:01,301] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:12:01,301] logger.py-->error_log line:11 [ERROR] 热加载报错热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:12:01,301] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:12:01,301] logger.py-->error_log line:11 [ERROR] 发送请求报错热加载报错热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:12:01,301] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:12:01,316] logger.py-->print_log line:17 [INFO] ----------接口测试开始-----------
[2022-06-15 22:12:01,316] logger.py-->print_log line:17 [INFO] MD5登录sdcard登录-type为空
[2022-06-15 22:12:01,316] logger.py-->print_log line:17 [INFO] 接口请求方式post
[2022-06-15 22:12:01,316] logger.py-->print_log line:17 [INFO] 接口请求路径http://jazz.wifi/api.cgi?path=account&method=login
[2022-06-15 22:12:01,316] logger.py-->error_log line:11 [ERROR] 热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:12:01,316] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:12:01,316] logger.py-->error_log line:11 [ERROR] 热加载报错热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:12:01,316] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:12:01,316] logger.py-->error_log line:11 [ERROR] 发送请求报错热加载报错热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:12:01,316] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:12:01,347] logger.py-->print_log line:17 [INFO] ----------接口测试开始-----------
[2022-06-15 22:12:01,347] logger.py-->print_log line:17 [INFO] 获取登录信息
[2022-06-15 22:12:01,347] logger.py-->print_log line:17 [INFO] 接口请求方式post
[2022-06-15 22:12:01,347] logger.py-->print_log line:17 [INFO] 接口请求路径http://jazz.wifi/api.cgi?path=account&method=get_info
[2022-06-15 22:12:01,347] logger.py-->error_log line:11 [ERROR] 热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:12:01,347] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:12:01,347] logger.py-->error_log line:11 [ERROR] 热加载报错热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:12:01,347] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:12:01,347] logger.py-->error_log line:11 [ERROR] 发送请求报错热加载报错热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:12:01,347] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:12:01,363] logger.py-->print_log line:17 [INFO] ----------接口测试开始-----------
[2022-06-15 22:12:01,363] logger.py-->print_log line:17 [INFO] 获取登陆剩余尝试次数和超出次数的锁定时间
[2022-06-15 22:12:01,363] logger.py-->print_log line:17 [INFO] 接口请求方式post
[2022-06-15 22:12:01,363] logger.py-->print_log line:17 [INFO] 接口请求路径http://jazz.wifi/api.cgi?path=account&method=get_login_status
[2022-06-15 22:12:01,363] logger.py-->error_log line:11 [ERROR] 热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:12:01,363] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:12:01,363] logger.py-->error_log line:11 [ERROR] 热加载报错热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:12:01,363] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:12:01,363] logger.py-->error_log line:11 [ERROR] 发送请求报错热加载报错热加载报错'NoneType' object is not subscriptable
[2022-06-15 22:12:01,363] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:12:01,394] logger.py-->print_log line:17 [INFO] ----------接口测试开始-----------
[2022-06-15 22:12:01,394] logger.py-->print_log line:17 [INFO] 获取登录信息
[2022-06-15 22:12:01,394] logger.py-->print_log line:17 [INFO] 接口请求方式post
[2022-06-15 22:12:01,394] logger.py-->print_log line:17 [INFO] 接口请求路径http://jazz.wifi/api.cgi?path=account&method=set_info
[2022-06-15 22:12:01,394] logger.py-->print_log line:17 [INFO] 接口请求参数{'json': {'type': 'admin', 'username': 'admin', 'password': 'admin', 'total_time': 300}}
[2022-06-15 22:12:01,394] logger.py-->print_log line:17 [INFO] 接口请求参数{'headers': {'Origin': 'http://192.168.2.1', 'Referer': 'http://jazz.wifi/index.htm\\r\\n', 'X-Requested-With': 'XMLHttpRequest', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36'}}
[2022-06-15 22:12:01,394] logger.py-->error_log line:11 [ERROR] 发送请求报错HTTPConnectionPool(host='jazz.wifi', port=80): Max retries exceeded with url: /api.cgi?path=account&method=set_info (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C7AE068D90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
[2022-06-15 22:12:01,394] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

[2022-06-15 22:12:01,488] logger.py-->print_log line:17 [INFO] ----------接口测试开始-----------
[2022-06-15 22:12:01,488] logger.py-->print_log line:17 [INFO] 获取登陆剩余尝试次数和超出次数的锁定时间
[2022-06-15 22:12:01,488] logger.py-->print_log line:17 [INFO] 接口请求方式post
[2022-06-15 22:12:01,488] logger.py-->print_log line:17 [INFO] 接口请求路径http://jazz.wifi/api.cgi?path=account&method=get_retrytimes_and_time
[2022-06-15 22:12:01,488] logger.py-->print_log line:17 [INFO] 接口请求参数{'json': {'type': 'admin'}}
[2022-06-15 22:12:01,488] logger.py-->print_log line:17 [INFO] 接口请求参数{'headers': {'Origin': 'http://192.168.2.1', 'Referer': 'http://jazz.wifi/index.htm\\r\\n', 'X-Requested-With': 'XMLHttpRequest', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36'}}
[2022-06-15 22:12:01,504] logger.py-->error_log line:11 [ERROR] 发送请求报错HTTPConnectionPool(host='jazz.wifi', port=80): Max retries exceeded with url: /api.cgi?path=account&method=get_retrytimes_and_time (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C7AEA52D60>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
[2022-06-15 22:12:01,504] logger.py-->print_log line:17 [INFO] ----------接口请求结束----------

